### PR TITLE
Enable lints and improve code quality

### PR DESCRIPTION
**Pull request by leddy231**
**Type of change**

- [ ] New feature
- [x] Bug fix
- [x] Code Quality 
- [ ] Security patch
- [ ] Documentation update

**Description**

This PR:
* Adds and enables the [lints](https://pub.dev/packages/lints) package
* Resolves the lint warnings reported
* Resolves a bug at line 62 in test/personnummer.dart (`"format"` was used instead of `format`) thanks to a linter warning

To make it clear why the changes was made each lint warning is resolved in its own commit.
`no_leading_underscores_for_local_identifiers` rule is ignored for now, i plan to propose a slight refactor to the parsing function in a separate PR instead.

**Motivation**

Improves code quality and resolves a bug

**Checklist**

- [x] I have read the **CONTRIBUTING** document.
- [x] I have read and accepted the **Code of conduct**
- [x] Tests passes.
- [x] Style lints passes.

### CODE REVIEW

**Comment by frozzare** [comment]
Thanks for your pull request, looks good but the build isn’t working due to that lint package requires a different dart versions. It’s fine to bump our version :)

**Comment by leddy231** [comment]
Strange, I thought `pub` would not add a dependency with a version that is incompatible with the sdk constraints.
I have updated the image in the workflow to use the latest Dart version https://hub.docker.com/_/dart, should i bump the min required version in pubspec.yaml aswell? :smile:

**Comment by frozzare** [comment]
Hm, the workflow didn't work with the new image `pub: not found`

**Comment by leddy231** [comment]
Ah, forgot that they canged the `pub` command to `dart pub`.
Updated the workflow, and it runs to completion locally
image

**Comment by frozzare** [comment]
Awesome. Now it works, merging :)

**Pull request merged**
